# Netlify build configuration
[build]
  command = "npm run build"
  publish = "docs"
  functions = "netlify/functions"

# Redirect rule for Single Page Applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200