# netlify.toml

# This section explicitly sets your build command and publish directory.
[build]
  command = "npm run build"
  publish = "docs"

# This section is the critical fix. It forces the build system
# to fetch all Git LFS tracked files.
[build.lfs]
  fetch_include = "*"